env:
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  semi:
    - 2
    - never
  quotes:
    - 2
    - single
    - avoidEscape: true
  object-curly-spacing:
    - 2
    - always
  space-before-function-paren:
    - 2
    - always
